spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/rentflow
    username: rentflow
    password: rentflow
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 20000

  jpa:
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.rentflow: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.jdbc: DEBUG
    org.springframework.boot.context.config: DEBUG

jwt:
  secret: ${JWT_SECRET:}

encryption:
  secret-key: ${ENCRYPTION_SECRET_KEY:}

rentflow:
  file:
    signed-url:
      secret: ${RENTFLOW_FILE_SIGNED_URL_SECRET:rentflow-local-file-signed-url-secret-1234567890}

server:
  port: 8087
