package com.rentflow.common.idempotency.service;

public enum IdempotencyScope {
    CREATE_BOOKING,
    CANCEL_BOOKING,
    HOST_APPROVE_BOOKING,
    HOST_REJECT_BOOKING,
    HOST_EXPIRE_BOOKING_APPROVAL,
    AUTHORIZE_PAYMENT,
    SIMULATE_TRANSFER_CONFIRMATION,
    CAPTURE_PAYMENT,
    VOID_PAYMENT,
    REFUND_PAYMENT,
    RECONCILE_PAYMENT
}
